{% set name = "particlespy" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1e12833ac5b4e0e519a9c4b2c87f54a60ad2cab49587a8295e4a6a596b61836f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3
    - setuptools
  run:
    - hyperspy
    - pyqt
    - python >=3
    - scikit-image >=0.15

test:
  imports:
    - ParticleSpy

about:
  home: https://github.com/ePSIC-DLS/ParticleSpy
  license: GPL-3.0
  license_file: LICENSE
  summary: A package to perform particle segmentation and analysis
  doc_url: https://epsic-dls.github.io/ParticleSpy/index.html

extra:
  recipe-maintainers:
    - tschoonj
